name: Cypress tests running on a pipeline
on: 
  push:
    branches: 
          - 'main'
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download dependencies
        run: npm install use-force-update

      - name: Download dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Build
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v2